### PR TITLE
added option to remove ID values

### PR DESCRIPTION
**Pull request by grouchal**
[Coverage Status](https://coveralls.io/github/tjw-lint/jest-serializer-vue-tjw?branch=BRANCHNAME)

* [x] Functionality
* [x] Tests
* [x] Documentation
* [ ] Version bump
* [ ] Update deps

### CODE REVIEW

**Comment by grouchal** [comment]
I have created this pull request to add what would be a very useful to stop the serialiser from writing out ID values. This is useful when the values change on each build.

**Comment by grouchal** [comment]
related issue #56

**Comment by TheJaredWilcurt** [comment]
I'm not seeing a reason to do this for ID's specifically. If this feature were to be added, I'd rather it be something more generic, like `attributesToClear: ['id', 'title']`.

```diff
-<div class="fluffy mittens" id="cat" title="meow"></div>
+<div class="fluffy mittens" id title></div>
```

**Comment by dcrystalj** [comment]
Is there any way you can add support for setting this per-test ?
I dont want to remove id tag for all tests in the project, just specific one.

**Comment by TheJaredWilcurt** [comment]
Currently there are no per-test (or per-snapshot) settings. Everything is global. The only sort-of exception is with features that require a VNode. You can opt-in to them globally, and then opt-out of all VNode based features in a single snapshot by passing in `wrapper.html()` instead of `wrapper`. But that's less of a setting and more of a requirement for that feature to work.

I'm not sure how to pass settings to the serializer from the individual test.

**Comment by TheJaredWilcurt** [comment]
You can mock the global settings file in one test and customize the the settings for it:

https://github.com/tjw-lint/jest-serializer-vue-tjw#faqs--tips

We use a helper function in the tests in this repo to do the same thing.

**Pull request closed without merging**
